### ISSUE TITLE
Issue "staleness" indicator in the Issues view

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/dashboard#1]
## What happened?

Please provide some details about the task you are trying to accomplish and
what went wrong.

* What were you attempting to do?
 I was looking at the Issues page on the dashboard, and I wanted to see not just how old issues are, but how "stale" they are (i.e. when the last comment happened on them)

* What did you expect to happen?
I expected some indication in the UI to indicate either the date of the most recent activity on the issue, or some kind of color coding on the number of comments to suggest staleness.

I think this would be helpful in eyeballing which issues should be closed and/or triaged first.

**Comment by robdimsdale** [comment]
+1 - I just found myself wanting exactly this feature. I want to be able to order issues by last response, not just creation time.

**Comment by fg-j** [comment]
fwiw Paketo's Triage Party instance can do this https://triage-party-ngfy5sbarq-uc.a.run.app/s/weekly

**Comment by robdimsdale** [comment]
Triage party can solve this, and additionally I'm exploring other options to interact with issues based on staleness (e.g. https://github.com/dlvhdr/gh-dash).

I'm going to close this issue as it is unlikely we will implement this feature in the dashboard.
